openapi: 3.0.0
info:
  title: ''
  version: ''
  contact: {}
  description: |-
    <details><summary style="font-size:1.75em;">API一覧</summary><div>

    | URL                           | メソッド | API名                |
    | :---------------------------- | :------- | :------------------- |
    | /api/auth/{socialType}            | POST     | ソーシャルログイン   |
    | /api/user/{uid}      | GET      | ユーザー情報取得 |
    | /api/user/{uid}      | POST     | ユーザー情報更新     |
    | /api/user/follow/{uid}    | JSON     | フォロー一覧取得     |
    | /api/user/follow/{uid}   | POST     | フォロー更新         |
    | /api/user/follower/{uid} | GET      | フォロワー一覧取得   |
    | /api/user/follower/{uid} | POST     | フォロワー更新       |
    | /api/tag/{tagname} | GET      | タグ一覧取得         |
    | /api/service/{serviceName}                | GET      | サービス一覧取得         |
    | /api/nortification/{uid} | GET      | 通知一覧取得             |
    | /api/nortification/{uid} | POST     | 通知フラグ更新       |
    | /api/setting/profile/{uid}    | GET      | プロフィール設定取得 |
    | /api/setting/profile/{uid}    | POST     | プロフィール設定更新 |
    | /api/setting/account/{uid}    | GET      | アカウント設定取得   |
    | /api/setting/account/{uid}    | POST     | アカウント設定更新   |
    | /api/setting/nortification/{uid}  | GET      | 通知設定取得         |
    | /api/setting/nortification/{uid}  | POST     | 通知設定更新         |
    | /api/setting/customize/{uid}  | GET      | 表示設定取得         |
    | /api/setting/customize/{uid}  | POST     | 表示設定更新         |

    </div></details>
servers:
  - url: 'http://localhost:8080'
    description: 開発環境
paths:
  '/api/auth/{socialType}':
    post:
      summary: ソーシャルログイン
      operationId: post-login
      responses:
        '200':
          description: OK
        default:
          $ref: '#/components/responses/commonError'
      description: ログインを行う
      tags:
        - /api/auth/
    parameters:
      - schema:
          type: string
        name: socialType
        in: path
        required: true
        description: ログインに使用するサービスの種類
  '/api/user/{uid}':
    get:
      summary: ユーザー情報取得
      tags:
        - /api/user/
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userInfoRequired'
        default:
          $ref: '#/components/responses/commonError'
      operationId: get-login
      description: ユーザーの詳細の取得
      parameters: []
    parameters:
      - $ref: '#/components/parameters/uid'
    post:
      summary: ユーザー情報更新
      tags:
        - /api/user/
      operationId: post-api-user-userid
      responses:
        '200':
          description: OK
        default:
          $ref: '#/components/responses/commonError'
      description: ユーザーの更新
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: ユーザー情報の差分
              properties:
                userid:
                  $ref: '#/components/schemas/userid'
                uname:
                  $ref: '#/components/schemas/uname'
                umail:
                  $ref: '#/components/schemas/umail'
                udesc:
                  $ref: '#/components/schemas/udesc'
                uimgpath:
                  $ref: '#/components/schemas/uimgpath'
  '/api/user/follow/{uid}':
    get:
      summary: フォロー一覧取得
      tags:
        - /api/user/follow/
      responses:
        '200':
          $ref: '#/components/responses/userList'
        default:
          $ref: '#/components/responses/commonError'
      operationId: get-@-userid-follow
      description: そのユーザーのフォロー一覧を取得する
    parameters:
      - $ref: '#/components/parameters/uid'
    post:
      summary: フォロー更新
      tags:
        - /api/user/follow/
      operationId: post-api-user-follow-userid
      responses:
        '200':
          description: OK
        default:
          $ref: '#/components/responses/commonError'
      description: そのユーザーのフォローを更新する
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                followid:
                  type: string
                  description: フォロー/フォロワー更新するユーザーの固有ID
                followerid:
                  type: string
                  description: ログイン中のユーザーの固有ID
              required:
                - followid
                - followerid
  '/api/user/follower/{uid}':
    get:
      summary: フォロワー一覧取得
      tags:
        - /api/user/follower/
      responses:
        '200':
          $ref: '#/components/responses/userList'
        default:
          $ref: '#/components/responses/commonError'
      operationId: get-@-userid-follower
      description: そのユーザーのフォロワーの一覧を取得する
    parameters:
      - $ref: '#/components/parameters/uid'
    post:
      summary: フォロワー更新
      tags:
        - /api/user/follower/
      operationId: post-api-user-follower-userid
      responses:
        '200':
          description: OK
        default:
          $ref: '#/components/responses/commonError'
      description: そのユーザーのフォロワーを更新する
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                followid:
                  type: string
                  description: ログイン中のユーザーの固有ID
                followerid:
                  type: string
                  description: フォロー/フォロワー更新するユーザーの固有ID
              required:
                - followid
                - followerid
  '/api/tag/{tagname}':
    parameters:
      - schema:
          type: string
        name: tagname
        in: path
        required: true
        description: タグ名
    get:
      summary: タグ一覧取得
      responses:
        '200':
          $ref: '#/components/responses/userList'
        default:
          $ref: '#/components/responses/commonError'
      operationId: 'get-tag-#-tagname'
      tags:
        - /api/tag/
      description: 'そのタグをタグ付けしている人の一覧を取得する '
  '/api/app/{aname}':
    parameters:
      - schema:
          type: string
        name: aname
        in: path
        required: true
        description: アプリ名
    get:
      summary: アプリ一覧取得
      responses:
        '200':
          $ref: '#/components/responses/userList'
        default:
          $ref: '#/components/responses/commonError'
      operationId: get-api-app-aname
      tags:
        - /api/service/
      description: アプリを登録しているユーザーの一覧を取得する
  "/api/nortification/{uid}'":
    get:
      summary: 通知取得
      tags:
        - /api/nortification/
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: 通知リスト
                items:
                  type: object
                  description: 通知
                  properties:
                    nid:
                      type: string
                      description: 通知ID
                    ntitle:
                      type: string
                      description: タイトル
                    ndetail:
                      type: string
                      description: 詳細
                    ntype:
                      type: string
                      description: カテゴリ
                    ndate:
                      type: string
                      description: 通知日時
                      format: date-time
                  required:
                    - nid
                    - ntitle
                    - ndetail
                    - ntype
                    - ndate
        default:
          $ref: '#/components/responses/commonError'
      operationId: get-nortification
      description: 通知
    post:
      summary: 通知フラグ更新
      tags:
        - /api/nortification/
      operationId: post-api-nortification
      responses:
        '200':
          description: OK
        default:
          $ref: '#/components/responses/commonError'
      description: 開いた際に通知フラグを更新する
      requestBody:
        content:
          application/json:
            schema:
              type: array
              description: 通知IDリスト
              items:
                type: string
                description: 通知ID
        description: ''
    parameters:
      - $ref: '#/components/parameters/uid'
  '/api/setting/profile/{uid}':
    get:
      summary: プロフィール設定取得
      tags:
        - /api/setting/profile/
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: プロフィール設定
                properties:
                  sid:
                    type: integer
                    description: 設定ID
        default:
          $ref: '#/components/responses/commonError'
      operationId: get-setting-profile
      description: プロフィール設定
      security:
        - key: []
    post:
      summary: プロフィール設定更新
      tags:
        - /api/setting/profile/
      operationId: post-api-setting-profile
      responses:
        '200':
          description: OK
        default:
          $ref: '#/components/responses/commonError'
      description: そのユーザーのプロフィール設定を更新する
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: プロフィール設定
              properties:
                sid:
                  type: integer
                  description: 設定ID
    parameters:
      - $ref: '#/components/parameters/uid'
  '/api/setting/account/{uid}':
    get:
      summary: アカウント設定取得
      tags:
        - /api/setting/account/
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: アカウント設定
                properties:
                  sid:
                    type: integer
                    description: 設定ID
        default:
          $ref: '#/components/responses/commonError'
      operationId: get-setting-account
      description: そのユーザーのアカウント設定を更新する
      security:
        - key: []
    post:
      summary: アカウント設定更新
      tags:
        - /api/setting/account/
      operationId: post-api-setting-account
      responses:
        '200':
          description: OK
        default:
          $ref: '#/components/responses/commonError'
      description: そのユーザーのアカウント設定を更新する
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: アカウント設定
              properties:
                sid:
                  type: integer
                  description: 設定ID
    parameters:
      - $ref: '#/components/parameters/uid'
  '/api/setting/nortification/{uid}':
    get:
      summary: 通知設定取得
      tags:
        - /api/setting/nortification/
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: 通知設定
                properties:
                  sid:
                    type: integer
                    description: 設定ID
        default:
          $ref: '#/components/responses/commonError'
      operationId: get-setting-nortification
      description: そのユーザーの通知設定を取得する
      security:
        - key: []
    post:
      summary: 通知設定更新
      tags:
        - /api/setting/nortification/
      operationId: post-api-setting-nortification
      responses:
        '200':
          description: OK
        default:
          $ref: '#/components/responses/commonError'
      description: そのユーザーの通知設定更新
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: 通知設定
              properties:
                sid:
                  type: integer
                  description: 設定ID
    parameters:
      - $ref: '#/components/parameters/uid'
  '/api/setting/customize/{uid}':
    get:
      summary: 表示設定取得
      tags:
        - /api/setting/customize/
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: 表示設定
                properties:
                  sid:
                    type: integer
                    description: 設定ID
        default:
          $ref: '#/components/responses/commonError'
      operationId: get-setting-customize
      description: 表示(デザイン)設定
      security:
        - key: []
    post:
      summary: 表示設定更新
      tags:
        - /api/setting/customize/
      operationId: post-api-setting-customize
      responses:
        '200':
          description: OK
        default:
          $ref: '#/components/responses/commonError'
      description: そのユーザーの表示(デザイン)設定を更新する
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: 表示設定
              properties:
                sid:
                  type: integer
                  description: 設定ID
    parameters:
      - $ref: '#/components/parameters/uid'
components:
  schemas:
    uid:
      type: integer
    userid:
      type: string
      description: ユーザーID
    uname:
      type: string
      description: ユーザー名
    umail:
      type: string
      description: メールアドレス
    udesc:
      type: string
      description: ユーザー説明
    uimgpath:
      type: string
      description: ユーザー画像パス
    userInfoRequired:
      type: object
      description: ユーザー情報
      properties:
        userid:
          $ref: '#/components/schemas/userid'
        uname:
          $ref: '#/components/schemas/uname'
        umail:
          $ref: '#/components/schemas/umail'
        udesc:
          $ref: '#/components/schemas/udesc'
        uimgpath:
          $ref: '#/components/schemas/uimgpath'
      required:
        - userid
        - uname
        - umail
        - udesc
        - uimgpath
    userListRequired:
      type: array
      description: ユーザー一覧
      items:
        $ref: '#/components/schemas/userInfoRequired'
    error:
      type: object
      description: エラー内容
      properties:
        code:
          type: string
          description: エラーコード
        message:
          type: string
          description: エラーメッセージ
      required:
        - code
        - message
  parameters:
    uid:
      schema:
        $ref: '#/components/schemas/uid'
      name: uid
      in: path
      required: true
      description: ログイン中のユーザーの固有ID
  responses:
    userList:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/userListRequired'
    commonError:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
  securitySchemes:
    key:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: AuthrizationURL
          tokenUrl: TokenURL
          refreshUrl: RefreshUrl
          scopes: {}
        clientCredentials:
          tokenUrl: TokenURL
          refreshUrl: RefreshURL
          scopes:
            scope_1: description
tags:
  - name: /api/auth/
  - name: /api/user/
  - name: /api/user/follow/
  - name: /api/user/follower/
  - name: /api/tag/
  - name: /api/service/
  - name: /api/nortification/
  - name: /api/setting/profile/
  - name: /api/setting/account/
  - name: /api/setting/nortification/
  - name: /api/setting/customize/
