openapi: 3.0.0
info:
  title: ''
  version: ''
  description: |-
    <details><summary style="font-size:1.75em;">API一覧</summary><div>

    |URL|メソッド|種類|API名|
    |:-|:-|:-|:-|
    |/top|GET|画面|TOP画面|
    |/@{userId}|GET|画面|ユーザー詳細情報画面|
    |/@{userId}|POST|API|ユーザー情報更新|
    |/@{userId}/follow|GET|画面|フォロー一覧画面|
    |/@{userId}/follow/@{userId}|POST|API|フォロー更新|
    |/@{userId}/follower|GET|画面|フォロワー一覧画面|
    |/@{userId}/follower/@{userId}|POST|API|フォロワー更新|
    |/tag/{tagName}|GET|画面|タグ一覧画面|
    |/nortification|GET|画面|通知画面|
    |/nortification/{norId}|POST|API|通知フラグ更新|
    |/settings/profile|GET|画面|プロフィール設定画面|
    |/settings/profile|POST|API|プロフィール設定更新|
    |/settings/account|GET|画面|アカウント設定画面|
    |/settings/account|POST|API|アカウント設定更新|
    |/settings/nortification|GET|画面|通知設定画面|
    |/settings/nortification|POST|API|通知設定更新|
    |/settings/customize|GET|画面|表示設定画面|
    |/settings/customize|POST|API|表示設定更新|
    |/help|GET|画面|ヘルプ画面|
    |/terms|GET|画面|利用規約|

    </div></details>
  # license:
  #   name: GNU General Public License v3.0
  #   url: 'https://www.gnu.org/licenses/gpl-3.0.html'
  # contact: {}
  # termsOfService: 'https://undesided.terms.url'
servers:
  - url: 'http://localhost:8080'
    description: 開発環境
paths:
  /top:
    get:
      summary: トップ画面
      tags:
        - 画面
      responses: {}
      operationId: get-top
      description: トップ画面(ログイン、紹介)
  '/@{userId}':
    get:
      summary: ユーザー情報詳細画面
      tags:
        - 画面
      responses:
        '200':
          description: OK
          content:
            text/html:
              ref: '#/components/schemas/defaulthtml'
              schema:
                $ref: '#/components/schemas/defaulthtml'
      operationId: get-login
      description: ユーザーの詳細(ログイン時トップリダイレクト)
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
        description: ユーザーID
  '/@{userId}/follow':
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
        description: ユーザーID
    get:
      summary: フォロー一覧画面
      tags:
        - 画面
      responses:
        '200':
          description: OK
          content:
            text/html:
              ref: '#/components/schemas/defaulthtml'
              schema:
                $ref: '#/components/schemas/defaulthtml'
      operationId: get-@-userId-follow
      description: そのユーザーのフォロー一覧
  '/@{userId}/follower':
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
        description: ユーザーID
    get:
      summary: フォロワー一覧画面
      tags:
        - 画面
      responses:
        '200':
          description: OK
          content:
            text/html:
              ref: '#/components/schemas/defaulthtml'
              schema:
                $ref: '#/components/schemas/defaulthtml'
      operationId: get-@-userId-follower
      description: そのユーザーのフォロワーの一覧
  '/tag/{tagName}':
    parameters:
      - schema:
          type: string
        name: tagName
        in: path
        required: true
        description: タグ名
    get:
      summary: タグ一覧画面
      tags:
        - 画面
      responses:
        '200':
          description: OK
          content:
            text/html:
              ref: '#/components/schemas/defaulthtml'
              schema:
                $ref: '#/components/schemas/defaulthtml'
      operationId: 'get-tag-#-tagname'
  /nortification:
    get:
      summary: 通知画面
      tags:
        - 画面
      responses:
        '200':
          description: OK
          content:
            text/html:
              ref: '#/components/schemas/defaulthtml'
              schema:
                $ref: '#/components/schemas/defaulthtml'
      operationId: get-nortification
      description: 通知
      security:
        - key: []
  /settings/profile:
    get:
      summary: プロフィール設定画面
      tags:
        - 画面
      responses:
        '200':
          description: OK
          content:
            text/html:
              ref: '#/components/schemas/defaulthtml'
              schema:
                $ref: '#/components/schemas/defaulthtml'
      operationId: get-settings-profile
      description: プロフィール設定
      security:
        - key: []
  /settings/account:
    get:
      summary: アカウント設定画面
      tags:
        - 画面
      responses:
        '200':
          description: OK
          content:
            text/html:
              ref: '#/components/schemas/defaulthtml'
              schema:
                $ref: '#/components/schemas/defaulthtml'
      operationId: get-settings-account
      description: アカウント設定
      security:
        - key: []
  /settings/nortification:
    get:
      summary: 通知設定画面
      tags:
        - 画面
      responses:
        '200':
          description: OK
          content:
            text/html:
              ref: '#/components/schemas/defaulthtml'
              schema:
                $ref: '#/components/schemas/defaulthtml'
      operationId: get-settings-nortification
      description: 通知設定
      security:
        - key: []
  /settings/customize:
    get:
      summary: 表示設定画面
      tags:
        - 画面
      responses:
        '200':
          description: OK
          content:
            text/html:
              ref: '#/components/schemas/defaulthtml'
              schema:
                $ref: '#/components/schemas/defaulthtml'
      operationId: get-settings-customize
      description: 表示(デザイン)設定
      security:
        - key: []
  /help:
    get:
      summary: ヘルプ画面
      tags:
        - 画面
      responses:
        '200':
          description: OK
          content:
            text/html:
              ref: '#/components/schemas/defaulthtml'
              schema:
                $ref: '#/components/schemas/defaulthtml'
      operationId: get-help
      description: マニュアル
  /terms:
    get:
      summary: 利用規約画面
      tags:
        - 画面
      responses:
        '200':
          description: OK
          content:
            text/html:
              ref: '#/components/schemas/defaulthtml'
              schema:
                $ref: '#/components/schemas/defaulthtml'
      operationId: get-terms
      description: 利用規約
  /api/test:
    parameters: []
components:
  schemas:
    defaulthtml:
      type: string
      description: HTML
  securitySchemes:
    key:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: AuthrizationURL
          tokenUrl: TokenURL
          refreshUrl: RefreshUrl
          scopes: {}
        clientCredentials:
          tokenUrl: TokenURL
          refreshUrl: RefreshURL
          scopes:
            scope_1: description
