openapi: 3.0.0
info:
  title: ''
  version: ''
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  /login:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-login
    post:
      summary: Your POST endpoint
      operationId: post-login
      responses:
        '200':
          description: OK
components:
  schemas: {}
