openapi: 3.0.0
info:
  title: ''
  version: ''
  contact: {}
  description: |-
    <details><summary style="font-size:1.75em;">API一覧</summary><div>

    | URL                           | メソッド | API名                |
    | :---------------------------- | :------- | :------------------- |
    | /api/auth/{socialType}            | POST     | ソーシャルログイン   |
    | /api/user/{userId}      | GET      | ユーザー情報取得 |
    | /api/user/{userId}      | POST     | ユーザー情報更新     |
    | /api/user/follow/{userId}    | JSON     | フォロー一覧取得     |
    | /api/user/follow/{userId}   | POST     | フォロー更新         |
    | /api/user/follower/{userId} | GET      | フォロワー一覧取得   |
    | /api/user/follower/{userId} | POST     | フォロワー更新       |
    | /api/tag/{tagName}                | GET      | タグ一覧取得         |
    | /api/nortification/{userId} | GET      | 通知一覧取得             |
    | /api/nortification/{userId} | POST     | 通知フラグ更新       |
    | /api/setting/profile/{userId}    | GET      | プロフィール設定取得 |
    | /api/setting/profile/{userId}    | POST     | プロフィール設定更新 |
    | /api/setting/account/{userId}    | GET      | アカウント設定取得   |
    | /api/setting/account/{userId}    | POST     | アカウント設定更新   |
    | /api/setting/nortification/{userId}  | GET      | 通知設定取得         |
    | /api/setting/nortification/{userId}  | POST     | 通知設定更新         |
    | /api/setting/customize/{userId}  | GET      | 表示設定取得         |
    | /api/setting/customize/{userId}  | POST     | 表示設定更新         |

    </div></details>
servers:
  - url: 'http://localhost:8080'
    description: 開発環境
paths:
  '/api/auth/{socialType}':
    post:
      summary: ソーシャルログイン
      operationId: post-login
      responses:
        '200':
          description: OK
        default:
          $ref: '#/components/responses/commonError'
      description: ログインを行う
      tags:
        - /api/auth/
    parameters:
      - schema:
          type: string
        name: socialType
        in: path
        required: true
        description: ログインに使用するサービスの種類
  '/api/user/{userId}':
    get:
      summary: ユーザー情報取得
      tags:
        - /api/user/
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userInfo'
        default:
          $ref: '#/components/responses/commonError'
      operationId: get-login
      description: ユーザーの詳細の取得
      parameters: []
    parameters:
      - $ref: '#/components/parameters/user'
    post:
      summary: ユーザー情報更新
      tags:
        - /api/user/
      operationId: post-api-user-userId
      responses:
        '200':
          description: OK
        default:
          $ref: '#/components/responses/commonError'
      description: ユーザーの更新
  '/api/user/follow/{userId}':
    get:
      summary: フォロー一覧取得
      tags:
        - /api/user/follow/
      responses:
        '200':
          $ref: '#/components/responses/userList'
        default:
          $ref: '#/components/responses/commonError'
      operationId: get-@-userId-follow
      description: そのユーザーのフォロー一覧を取得する
    parameters:
      - $ref: '#/components/parameters/user'
    post:
      summary: フォロー更新
      tags:
        - /api/user/follow/
      operationId: post-api-user-follow-userId
      responses:
        '200':
          description: OK
        default:
          $ref: '#/components/responses/commonError'
      description: そのユーザーのフォローを更新する
  '/api/user/follower/{userId}':
    get:
      summary: フォロワー一覧取得
      tags:
        - /api/user/follower/
      responses:
        '200':
          $ref: '#/components/responses/userList'
        default:
          $ref: '#/components/responses/commonError'
      operationId: get-@-userId-follower
      description: そのユーザーのフォロワーの一覧を取得する
    parameters:
      - $ref: '#/components/parameters/user'
    post:
      summary: フォロワー更新
      tags:
        - /api/user/follower/
      operationId: post-api-user-follower-userId
      responses:
        '200':
          description: OK
        default:
          $ref: '#/components/responses/commonError'
      description: そのユーザーのフォロワーを更新する
  '/api/tag/{tagName}':
    parameters:
      - schema:
          type: string
        name: tagName
        in: path
        required: true
        description: タグ名
    get:
      summary: タグ一覧取得
      responses:
        '200':
          $ref: '#/components/responses/userList'
        default:
          $ref: '#/components/responses/commonError'
      operationId: 'get-tag-#-tagname'
      tags:
        - /api/tag/
      description: 'そのタグをタグ付けしている人の一覧を取得する '
  "/api/nortification/{userId}'":
    get:
      summary: 通知取得
      tags:
        - /api/nortification/
      responses:
        '200':
          description: OK
          content:
            application/json: {}
        default:
          $ref: '#/components/responses/commonError'
      operationId: get-nortification
      description: 通知
      security:
        - key: []
    post:
      summary: 通知フラグ更新
      tags:
        - /api/nortification/
      operationId: post-api-nortification
      responses:
        '200':
          description: OK
        default:
          $ref: '#/components/responses/commonError'
      description: 開いた際に通知フラグを更新する
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                norId:
                  type: string
                  description: 通知ID
        description: ''
    parameters:
      - $ref: '#/components/parameters/user'
  '/api/setting/profile/{userId}':
    get:
      summary: プロフィール設定取得
      tags:
        - /api/setting/profile/
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
        default:
          $ref: '#/components/responses/commonError'
      operationId: get-setting-profile
      description: プロフィール設定
      security:
        - key: []
    post:
      summary: プロフィール設定更新
      tags:
        - /api/setting/profile/
      operationId: post-api-setting-profile
      responses:
        '200':
          description: OK
        default:
          $ref: '#/components/responses/commonError'
      description: そのユーザーのプロフィール設定を更新する
    parameters:
      - $ref: '#/components/parameters/user'
  '/api/setting/account/{userId}':
    get:
      summary: アカウント設定取得
      tags:
        - /api/setting/account/
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
        default:
          $ref: '#/components/responses/commonError'
      operationId: get-setting-account
      description: そのユーザーのアカウント設定を更新する
      security:
        - key: []
    post:
      summary: アカウント設定更新
      tags:
        - /api/setting/account/
      operationId: post-api-setting-account
      responses:
        '200':
          description: OK
        default:
          $ref: '#/components/responses/commonError'
      description: そのユーザーのアカウント設定を更新する
    parameters:
      - $ref: '#/components/parameters/user'
  '/api/setting/nortification/{userId}':
    get:
      summary: 通知設定取得
      tags:
        - /api/setting/nortification/
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
        default:
          $ref: '#/components/responses/commonError'
      operationId: get-setting-nortification
      description: そのユーザーの通知設定を取得する
      security:
        - key: []
    post:
      summary: 通知設定更新
      tags:
        - /api/setting/nortification/
      operationId: post-api-setting-nortification
      responses:
        '200':
          description: OK
        default:
          $ref: '#/components/responses/commonError'
      description: そのユーザーの通知設定更新
    parameters:
      - $ref: '#/components/parameters/user'
  '/api/setting/customize/{userId}':
    get:
      summary: 表示設定取得
      tags:
        - /api/setting/customize/
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
        default:
          $ref: '#/components/responses/commonError'
      operationId: get-setting-customize
      description: 表示(デザイン)設定
      security:
        - key: []
    post:
      summary: 表示設定更新
      tags:
        - /api/setting/customize/
      operationId: post-api-setting-customize
      responses:
        '200':
          description: OK
        default:
          $ref: '#/components/responses/commonError'
      description: そのユーザーの表示(デザイン)設定を更新する
    parameters:
      - $ref: '#/components/parameters/user'
components:
  schemas:
    userInfo:
      type: object
      description: ユーザー情報
      properties:
        userId:
          type: string
          description: ユーザーID
        userName:
          type: string
          description: ユーザー名
        userMail:
          type: string
          description: メールアドレス
        userDesc:
          type: string
          description: ユーザー説明
        userimg:
          type: string
          description: ユーザー画像バイナリ
          format: binary
    userList:
      type: array
      description: ユーザー一覧
      items:
        $ref: '#/components/schemas/userInfo'
    error:
      type: object
      description: エラー内容
      properties:
        errorCode:
          type: string
          description: エラーコード
        errorMessage:
          type: string
          description: エラーメッセージ
  parameters:
    user:
      schema:
        type: string
      name: userId
      in: path
      required: true
      description: ユーザーID
  responses:
    userList:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/userList'
    commonError:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
  securitySchemes:
    key:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: AuthrizationURL
          tokenUrl: TokenURL
          refreshUrl: RefreshUrl
          scopes: {}
        clientCredentials:
          tokenUrl: TokenURL
          refreshUrl: RefreshURL
          scopes:
            scope_1: description
tags:
  - name: /api/auth/
  - name: /api/user/
  - name: /api/user/follow/
  - name: /api/user/follower/
  - name: /api/tag/
  - name: /api/nortification/
  - name: /api/setting/profile/
  - name: /api/setting/account/
  - name: /api/setting/nortification/
  - name: /api/setting/customize/
