spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasouce.username=sa
spring.datasouce.password=
spring.datasource.sql-script-encoding=UTF-8
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.datasource.initialization-mode=ALWAYS
spring.datasource.data=classpath:TestData.sql
spring.jpa.hibernate.ddl-auto=create
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=
spring.security.oauth2.client.registration.google.redirect-uri=
spring.security.oauth2.client.registration.facebook.client-id=
spring.security.oauth2.client.registration.facebook.client-secret=
spring.security.oauth2.client.registration.facebook.scope=
spring.security.oauth2.client.registration.facebook.redirect-uri=
spring.security.oauth2.client.registration.twutter.client-id=
spring.security.oauth2.client.registration.twutter.client-secret=
spring.security.oauth2.client.registration.twutter.scope=
spring.security.oauth2.client.registration.twutter.redirect-uri=
spring.security.oauth2.client.provider.facebook.authorization-uri=
spring.security.oauth2.client.provider.facebook.token-uri=
spring.security.oauth2.client.provider.facebook.user-info-uri=