openapi: 3.0.0
info:
  title: ''
  version: ''
  contact: {}
  description: _
servers:
  - url: 'http://localhost:8080'
    description: 開発環境
paths:
  '/api/auth/{socialtype}':
    post:
      summary: '認証[未]'
      description: ソーシャルログイン
      operationId: post-login
      tags:
        - 共通
      responses:
        '200':
          $ref: '#/components/responses/commonResponse'
        default:
          $ref: '#/components/responses/commonResponse'
    parameters:
      - schema:
          type: string
        name: socialtype
        in: path
        required: true
        description: SNS種類
  /api/user:
    get:
      summary: ユーザー情報取得機能
      description: 指定したユーザー情報を返す
      operationId: get-user
      tags:
        - ユーザー情報
      parameters:
        - $ref: '#/components/parameters/userId'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userInfo'
          description: OK
        default:
          $ref: '#/components/responses/commonResponse'
    post:
      summary: ユーザー情報更新機能
      description: 指定したユーザー情報を更新する
      operationId: post-user
      tags:
        - ユーザー情報
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userInfo'
      responses:
        '200':
          $ref: '#/components/responses/commonResponse'
        default:
          $ref: '#/components/responses/commonResponse'
      security:
        - key:
          - '認証要'
  /api/user/app:
    get:
      summary: ユーザーアプリ一覧取得機能
      description: 指定したユーザーのアプリ情報一覧を取得する
      operationId: get-user-app
      tags:
        - ユーザーのアプリ関連情報
      parameters:
        - $ref: '#/components/parameters/userId'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                description: アプリ情報リスト
                items:
                  $ref: '#/components/schemas/appInfo'
          description: OK
        default:
          $ref: '#/components/responses/commonResponse'
    post:
      summary: 'ユーザーアプリ追加機能[未]'
      description: 指定したユーザーのアプリ情報を追加する
      operationId: post-user-app
      tags:
        - ユーザーのアプリ関連情報
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/appInfo'
      responses:
        '200':
          $ref: '#/components/responses/commonResponse'
        default:
          $ref: '#/components/responses/commonResponse'
      security:
        - key:
          - '認証要'
    patch:
      summary: 'ユーザーアプリ一覧更新機能[未]'
      description: 指定したユーザーのアプリ情報一覧を更新する
      operationId: patch-user-app
      tags:
        - ユーザーのアプリ関連情報
      responses:
        '200':
          $ref: '#/components/responses/commonResponse'
        default:
          $ref: '#/components/responses/commonResponse'
    delete:
      summary: 'ユーザーアプリ一覧削除[未]'
      description: 指定したユーザーのアプリ情報一覧を削除する
      operationId: delete-user-app
      tags:
        - ユーザーのアプリ関連情報
      parameters:
        - $ref: '#/components/parameters/userId'
      responses:
        '200':
          $ref: '#/components/responses/commonResponse'
        default:
          $ref: '#/components/responses/commonResponse'
      security:
        - key:
          - '認証要'
  /api/user/follow:
    get:
      summary: フォロー情報一覧取得機能
      description: 指定したユーザーのフォロー一覧を返す
      operationId: get-user-follow
      tags:
        - ユーザーのユーザー関連情報
      parameters:
        - $ref: '#/components/parameters/userId'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/userInfo'
          description: OK
        default:
          $ref: '#/components/responses/commonResponse'
    post:
      summary: フォロー情報追加機能
      description: 指定したユーザーをフォローする
      operationId: post-user-follow
      tags:
        - ユーザーのユーザー関連情報
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userId'
      responses:
        '200':
          $ref: '#/components/responses/commonResponse'
        default:
          $ref: '#/components/responses/commonResponse'
      security:
        - key:
          - '認証要'
    delete:
      summary: フォロー情報削除機能
      description: 指定したユーザーをフォロー解除する
      operationId: delete-user-follow
      tags:
        - ユーザーのユーザー関連情報
      parameters:
        - $ref: '#/components/parameters/userId'
      responses:
        '200':
          $ref: '#/components/responses/commonResponse'
        default:
          $ref: '#/components/responses/commonResponse'
      security:
        - key:
          - '認証要'
  /api/user/follower:
    get:
      summary: フォロワー情報一覧取得機能
      description: 指定したユーザーのフォロワー一覧を返す
      operationId: get-user-follower
      tags:
        - ユーザーのユーザー関連情報
      parameters:
        - $ref: '#/components/parameters/userId'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/userInfo'
          description: OK
        default:
          $ref: '#/components/responses/commonResponse'
  /api/appList:
    get:
      summary: アプリ情報一覧取得機能
      description: アプリ情報一覧を返す
      operationId: get-applist
      tags:
        - アプリ情報
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                description: アプリ情報リスト
                items:
                  $ref: '#/components/schemas/appInfo'
          description: OK
        default:
          $ref: '#/components/responses/commonResponse'
      security:
        - key:
          - '認証要'
  /api/app:
    get:
      summary: アプリ情報取得機能
      description: 指定したアプリ情報を返す
      operationId: get-app
      tags:
        - アプリ情報
      parameters:
        - $ref: '#/components/parameters/appId'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                description: アプリ情報リスト
                items:
                  $ref: '#/components/schemas/appInfo'
          description: OK
        default:
          $ref: '#/components/responses/commonResponse'
    post:
      summary: アプリ情報追加機能
      description: 指定したアプリ情報を追加する
      operationId: post-app
      tags:
        - アプリ情報
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/appInfo'
      responses:
        '200':
          $ref: '#/components/responses/commonResponse'
        default:
          $ref: '#/components/responses/commonResponse'
      security:
        - key:
          - '認証要'
    patch:
      summary: アプリ情報更新機能
      description: 指定したアプリ情報を更新する
      operationId: patch-app
      tags:
        - アプリ情報
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/appInfo'
      security:
        - key:
          - '認証要'
      responses:
        '200':
          $ref: '#/components/responses/commonResponse'
        default:
          $ref: '#/components/responses/commonResponse'
  /api/app/user:
    get:
      summary: アプリユーザー情報一覧取得機能
      description: 指定したアプリの登録ユーザー一覧を返す
      operationId: get-app-user
      tags:
        - アプリのユーザー関連情報
      parameters:
        - $ref: '#/components/parameters/appId'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/userInfo'
          description: OK
        default:
          $ref: '#/components/responses/commonResponse'
  /api/nortification:
    get:
      summary: 通知情報一覧取得機能
      description: 通知設定情報を返す
      operationId: get-nortification
      tags:
        - 通知情報
      parameters:
        - $ref: '#/components/parameters/nortificationId'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/nortificationInfo'
        default:
          $ref: '#/components/responses/commonResponse'
      security:
        - key:
          - '認証要'
    patch:
      summary: 通知情報更新機能
      description: 通知設定情報を更新する
      operationId: patch-nortification
      tags:
        - 通知情報
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/nortificationInfo'
      responses:
        '200':
          $ref: '#/components/responses/commonResponse'
        default:
          $ref: '#/components/responses/commonResponse'
      security:
        - key:
          - '認証要'
  /api/setting/profile:
    get:
      summary: プロフィール設定取得
      tags:
        - 設定情報
      responses:
        '200':
          $ref: '#/components/responses/getSettings'
        default:
          $ref: '#/components/responses/commonResponse'
      operationId: get-setting-profile
      description: プロフィール設定情報を返す
      security:
        - key:
          - '認証要'
    patch:
      summary: プロフィール設定更新
      tags:
        - 設定情報
      operationId: post-api-setting-profile
      responses:
        '200':
          $ref: '#/components/responses/commonResponse'
        default:
          $ref: '#/components/responses/commonResponse'
      description: プロフィール設定を更新する
      requestBody:
        $ref: '#/components/requestBodies/settings'
      security:
        - key:
          - '認証要'
  /api/setting/account:
    get:
      summary: アカウント設定取得
      tags:
        - 設定情報
      responses:
        '200':
          $ref: '#/components/responses/getSettings'
        default:
          $ref: '#/components/responses/commonResponse'
      operationId: get-setting-account
      description: アカウント設定情報を返す
      security:
        - key:
          - '認証要'
    patch:
      summary: アカウント設定更新
      tags:
        - 設定情報
      operationId: post-api-setting-account
      responses:
        '200':
          $ref: '#/components/responses/commonResponse'
        default:
          $ref: '#/components/responses/commonResponse'
      description: アカウント設定を更新する
      requestBody:
        $ref: '#/components/requestBodies/settings'
      security:
        - key:
          - '認証要'
  /api/setting/nortification:
    get:
      summary: 通知設定取得
      tags:
        - 設定情報
      responses:
        '200':
          $ref: '#/components/responses/getSettings'
        default:
          $ref: '#/components/responses/commonResponse'
      operationId: get-setting-nortification
      description: 通知設定情報を返す
      security:
        - key:
          - '認証要'
    patch:
      summary: 通知設定更新
      tags:
        - 設定情報
      operationId: post-api-setting-nortification
      requestBody:
        $ref: '#/components/requestBodies/settings'
      responses:
        '200':
          $ref: '#/components/responses/commonResponse'
        default:
          $ref: '#/components/responses/commonResponse'
      description: 通知設定情報を更新する
      security:
        - key:
          - '認証要'
  /api/setting/customize:
    get:
      summary: 表示設定取得
      tags:
        - 設定情報
      responses:
        '200':
          $ref: '#/components/responses/getSettings'
        default:
          $ref: '#/components/responses/commonResponse'
      operationId: get-setting-customize
      description: 表示(デザイン)設定を返す
      security:
        - key:
          - '認証要'
    patch:
      summary: 表示設定更新
      tags:
        - 設定情報
      operationId: post-api-setting-customize
      responses:
        '200':
          $ref: '#/components/responses/commonResponse'
        default:
          $ref: '#/components/responses/commonResponse'
      description: 表示(デザイン)設定を更新する
      requestBody:
        $ref: '#/components/requestBodies/settings'
      security:
        - key:
          - '認証要'
tags:
  - name: 共通
  - name: ユーザー情報
  - name: ユーザーのアプリ関連情報
  - name: ユーザーのユーザー関連情報
  - name: アプリ情報
  - name: アプリのユーザー関連情報
  - name: 通知情報
  - name: 設定情報
components:
  requestBodies:
    settings:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/settings'
  parameters:
    userId:
      schema:
        type: string
      in: query
      name: userId
      description: ユーザーID
      required: true
    appId:
      schema:
        type: string
      in: query
      name: appId
      description: アプリID
      required: true
    nortificationId:
      schema:
        type: string
      in: query
      name: nortificationId
      description: 通知ID
      required: true
  responses:
    getSettings:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/settings'
    commonResponse:
      description: 共通レスポンス
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InfoResponse'
  securitySchemes:
    key:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: AuthrizationURL
          tokenUrl: TokenURL
          refreshUrl: RefreshUrl
          scopes: {}
        clientCredentials:
          tokenUrl: TokenURL
          refreshUrl: RefreshURL
          scopes:
            scope_1: description
  schemas:
    userId:
      type: string
      maxLength: 20
      description: ユーザーID
    userName:
      type: string
      maxLength: 20
      description: ユーザー名
    userDescription:
      type: string
      maxLength: 200
      description: ユーザー説明
    userImg:
      type: string
      description: ユーザー画像パス
    appId:
      type: string
      description: アプリID
    appName:
      type: string
      description: アプリ名
    appImg:
      type: string
      description: アプリ画像URL
    appUrl:
      type: string
      description: アプリURL
    settings:
      type: object
      description: 設定情報
      properties:
        setting1:
          type: string
          description: 設定値1
        setting2:
          type: integer
          description: 設定値2
    nortificationId:
      type: string
      description: 通知ID
    nortificationTitle:
      type: string
      description: 通知タイトル
    nortificationDate:
      type: string
      description: 通知日時
    nortificationTag:
      type: array
      description: 通知タグ
      items:
        type: string
    nortificationContent:
      type: string
      description: 通知内容
    nortificationFlag:
      type: boolean
      description: 通知フラグ
    appList:
      description: ユーザー関連アプリ情報1(優先表示)
      type: array
      items:
        type: object
        properties:
          appUrl:
            $ref: '#/components/schemas/appUrl'
          appImg:
            $ref: '#/components/schemas/appImg'
    userInfo:
      type: object
      properties:
        userId:
          $ref: '#/components/schemas/userId'
        userName:
          $ref: '#/components/schemas/userName'
        userDescription:
          $ref: '#/components/schemas/userDescription'
        userImg:
          $ref: '#/components/schemas/userImg'
        appList:
          $ref: '#/components/schemas/appList'
    appInfo:
      type: object
      description: アプリ
      properties:
        appId:
          $ref: '#/components/schemas/appId'
        appName:
          $ref: '#/components/schemas/appName'
        appImg:
          $ref: '#/components/schemas/appImg'
        appUrl:
          $ref: '#/components/schemas/appUrl'
    nortificationInfo:
      type: object
      description: 通知
      properties:
        nortificationId:
          $ref: '#/components/schemas/nortificationId'
        nortificationTitle:
          $ref: '#/components/schemas/nortificationTitle'
        nortificationDate:
          $ref: '#/components/schemas/nortificationDate'
        nortificationTag:
          $ref: '#/components/schemas/nortificationTag'
        nortificationContent:
          $ref: '#/components/schemas/nortificationContent'
        nortificationFlag:
          $ref: '#/components/schemas/nortificationFlag'
    InfoResponse:
      type: string
      description: レスポンスメッセージ
